- name: setup docker swarm 
  hosts: all
  become: yes 
  tasks:
    - name: To Update the Linux system 
      apt:  
        update_cache: yes

    - name: install docker 
      apt:
        name: docker.io
        state: present

    - name: install python3-pip
      apt:
        name: python3-pip
        state: present


    - name: install python "docker" library
      command: python3 -m pip install docker
      become: yes

- name: Check if the master node is in a swarm
  hosts: swarm_master
  become: yes
  tasks:
    - name: Check if the node is in a swarm
      shell: >
        docker info | egrep '^Swarm: ' | cut -d ' ' -f2
      register: swarm_status
      changed_when: false
      ignore_errors: true

- name: initializing the master node
  hosts: swarm_master
  become: yes 
  tasks:
    - name: get the join token for the master node only
      command: docker swarm join-token worker -q
      register: worker_token 
      when: "'active' not in swarm_status.stdout_lines"

    - name: initializing the master node
      command: docker swarm init
      when: inventory_hostname == groups['swarm_master'][0] and 'active' not in swarm_status.stdout_lines
      ignore_errors: true

- name: join worker hosts to swarm cluster
  hosts: worker_nodes
  become: yes
  tasks:
    - name: join worker nodes to cluster
      docker_swarm:
        state: join
        advertise_addr: "{{ ansible_host }}"          
        join_token: "{{ hostvars[groups['swarm_master'][0]]['worker_token']['stdout'] }}"
        remote_addrs: [ "{{ hostvars[groups['swarm_master'][0]]['ansible_default_ipv4']['address'] }}:2377" ]
